---
- name: Gather facts if they are missing
  ansible.builtin.setup:
  when: ansible_facts | length == 0

- name: Modify Linux PAM limits
  community.general.pam_limits:
    domain: '*'
    limit_type: "{{ type }}"
    limit_item: nofile
    value: 32768
  loop:
    - soft
    - hard
  loop_control:
    loop_var: type

- name: Install TAK Server on Debian
  ansible.builtin.include_tasks: "Debian/{{ item }}"
  loop:
    - prerequisites.yml
    - install.yml
    - post-configuration-cert.yml
    - post-configuration-config.yml
    - post-configuration-service.yml
    - post-configuration-webadmin.yml
    - post-configuration-firewall.yml
  when: ansible_facts['os_family'] == 'Debian'

# - name: Install TAK Server on RedHat
#   ansible.builtin.include_tasks: "RedHat/{{ item }}"
#   loop:
#     - prerequisites.yml
#     - install.yml
#     - post-configuration-cert.yml
#     - post-configuration-config.yml
#     - post-configuration-service.yml
#     - post-configuration-webadmin.yml
#     - post-configuration-firewall.yml
#   when: ansible_facts['os_family'] == 'RedHat'
