name: 'Ansible Lint'
on:
  pull_request:
    branches:
      - main
    paths:
      - 'defaults/**'
      - 'files/**'
      - 'handlers/**'
      - 'meta/**'
      - 'tasks/**'
      - 'vars/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ansible-lint:
    name: 'Ansible Lint'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run ansible-lint
        uses: ansible/ansible-lint@4114ad63edbc25dcd9afc4f41b29dbcbebdf21ca # v25.5.0
        with:
          args: >
            --sarif-file ansible-lint.sarif
          setup_python: true
          requirements_file: requirements.yml
        continue-on-error: true

      - name: Upload CodeQL sarif
        if: github.event_name == 'workflow_dispatch'
        uses: github/codeql-action/upload-sarif@60168efe1c415ce0f5521ea06d5c2062adbeed1b # v3.28.17
        with:
          sarif_file: "ansible-lint.sarif"
