name: ansible-lint
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run ansible-lint
        uses: ansible/ansible-lint@e98f9b38769d45cbe3c55a23b2eb25631babe7c4 # v25.4.0
        # optional (see below):
        with:
          args: >
            --sarif-file ansible-lint.sarif
          setup_python: true
          requirements_file: requirements.yml
        continue-on-error: true

      - name: Upload CodeQL sarif
        if: github.event_name == 'workflow_dispatch'
        uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
        with:
          sarif_file: "ansible-lint.sarif"
