name: 'Ansible Lint'
on:
  pull_request:
    branches:
      - main
    paths:
      - 'defaults/**'
      - 'files/**'
      - 'handlers/**'
      - 'meta/**'
      - 'tasks/**'
      - 'vars/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ansible-lint:
    name: 'Ansible Lint'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@61a8e7bad82cc7aee6d0981ea59831a95745795a # v25.11.1
        with:
          args: >
            --sarif-file ansible-lint.sarif
          setup_python: true
          requirements_file: requirements.yml
        continue-on-error: true

      - name: Upload CodeQL sarif
        if: github.event_name == 'workflow_dispatch'
        uses: github/codeql-action/upload-sarif@e296a935590eb16afc0c0108289f68c87e2a89a5 # v4.30.7
        with:
          sarif_file: "ansible-lint.sarif"
